### ISSUE TITLE
About training and evaluation code

### ISSUE THREAD

**Issue by YangJae96** [anDoer/PoseTrack21#14]
Hi. Thanks for your great work!

I was wondering how you trained and tested the person search model
with the PoseTrack datasets.

Did you use the other SOTA codes and make the code for the dataset preparing for training and testing?

If there is some code, could you provide it for research purpose?!

Thanks in advance.

**Comment by anDoer** [comment]
Hi, 

we used and adapted SOTA codes for training and testing. I will try to allocate some time on the weekend to release some code.

**Comment by YangJae96** [comment]
@anDoer  

Thank you!!

**Comment by anDoer** [comment]
@YangJae96 You can find the SeqNet baseline in the psearch_dev branch. Sorry that it took a little bit longer, I was busy with other duties.
