### ISSUE TITLE
about the detail of pose eval

### ISSUE THREAD

**Issue by WEIZHIHONG720** [anDoer/PoseTrack21#18]
Hi,  i used the api_example for the pose estimation , but there are some problems encountered：

<img width="903" alt="image" src="https://user-images.githubusercontent.com/43931281/226122570-337fb0fb-bf9c-425d-9469-e05064b31130.png">

in the line 34,  i can see the result data :
<img width="850" alt="image" src="https://user-images.githubusercontent.com/43931281/226122651-2ef4ad1e-8f89-44c3-9fff-32fd17a8dace.png">

but in the line 38, i got the error message:
AttributeError: 'dict' object has no attribute 'mean'.

In the results , i can see a attribute is 'total', does this attribute represent mean?
![image](https://user-images.githubusercontent.com/43931281/226122940-72439799-b9f3-46b5-90ec-49be1e4b612e.png)

**Comment by anDoer** [comment]
Thanks for reporting. 

`evaluator.get_avg_results()` is not supposed to be called for pose estimation. I'll push a fix.
