### ISSUE TITLE
Approval of Agreement

### ISSUE THREAD

**Issue by dae-sun** [anDoer/PoseTrack21#3]
I sent my agreement to posetrack21[at]googlegroups[dot]com a few days ago. but I didn't get the answer yet.
could you check the request? my email address is d****m@unist.ac.kr.

**Comment by jin-s13** [comment]
Same question. I sent my request on June 21th. But there is no response.

**Comment by anDoer** [comment]
@jin-s13 : We replied to your mail on 21st of June. Did you check your spam folder? I will re-send the token to your mail address. Please let me know if you recieved the token.
@dae-sun : We replied to your mail on 26th of July.

**Comment by qianxiaoye** [comment]
Hi . I have sent the agreement to posetrack21[at]googlegroups[dot]com a few week ago and also sent a new follow up email. But there is no response. My email address is xx********.edu. Could you please check that for me. Thank you so much for your help.

**Comment by qianxiaoye** [comment]
Hi Sir/Madam. I have sent the agreement to posetrack21[at]googlegroups[dot]com a few week ago and also sent a new follow up email. But there is no response. My email address is xx********.edu. Could you please check that for me. Thank you so much for your help.
