### ISSUE TITLE
Agreement Approval

### ISSUE THREAD

**Issue by qianxiaoye** [anDoer/PoseTrack21#8]
Hi Sir/Madam. I have sent the agreement to posetrack21[at]googlegroups[dot]com a few week ago and also sent a new follow up email. But there is no response. My email address is xx********.edu. Could you please check that for me. Thank you so much for your help.

**Comment by anDoer** [comment]
I'm sorry for the delay. I've sent you an e-mail. Please reach out again, if you did not receive it.

**Comment by qianxiaoye** [comment]
Received! Thank you so much for your help!
